### ISSUE TITLE
免费frp内网穿透 | Hexo

### ISSUE THREAD

**Issue by FleyX** [FleyX/technology-note#23]
https://www.tapme.top/blog/detail/2019-04-02-10-58/#more 

 &emsp;&emsp;公司调试需要公网 IP，遂在网上找了个免费的内网穿透–http://ku2.kerwin.cn/。延迟还行一百多毫秒。 使用方法下载软件&emsp;&emsp;首先下载 frp，下载地址：https://github.com/fatedier/frp/releases,选择对应的平台和版本，主要版本一定要和网站上的一致。

**Comment by ntgeralt** [comment]
楼主，这个好像失效了哦

**Comment by FleyX** [comment]
你需要内网穿透功能吗 @ntgeralt

**Comment by ntgeralt** [comment]
要呀，免费吗 :) https://t.me/ntGeralt
