### ISSUE TITLE
mysql全文检索 | FleyX's space

### ISSUE THREAD

**Issue by FleyX** [FleyX/technology-note#29]
https://www.tapme.top/blog/detail/2019-03-27-09-48/ 

 &emsp;&emsp;最近想给个人的项目加个全文检索，但是 VPS 的内存太捉急，在跑了一个 mysql，几个 node，和一个 java 后已经不足以再跑一个 es，所以就想着在 mysql 里做全文检索。 说明：mysql 的全文检索速度较慢，只适合小微系统临时使用。 &emsp;&emsp;从 MySQL 5.7.6 开始，MySQL 内置了 ngram 全文检索插件，用于支持中文分词，并

**Comment by BambooMBP** [comment]
速度较慢，可以具体给出数据么。mysql 5.7上，五百万数据的表，实测全文索引（ngram）（like %x%）耗时46ms，感觉挺不错的了啊

**Comment by FleyX** [comment]
mysql单表千万级的数据普通索引就很吃力了，全文检索就不用说了。es原生支持主从架构和数据分片，以支持更大量数据的全文检索。
