### ISSUE TITLE
最新ubuntu搭建公网个人邮件服务器(基于postfix，dovecot,mysql) | FleyX's space

### ISSUE THREAD

**Issue by FleyX** [FleyX/technology-note#35]
https://www.tapme.top/blog/detail/2019-04-05/ 

 &emsp;&emsp;最近做了一个应用，需要用邮件发通知，但是免费的邮箱每天发信数量是有限制的，所以呢就想着搭建一个自己的邮件服务器，能够实现邮件的发送和接收即可,其中大概花了一个星期找资料，测试，终于成功了，写个教程分享给大家。 &emsp;&emsp;本教程基于 ubuntu 18.04（其他的 linux 理论上也是可以的，知识安装的软件包不一样）。用到的主要软件为：postfix,dov

**Comment by imagemlt** [comment]
按你的文档搭建的服务器收不到邮件，也没办法用Mac自带邮件客户端来连接？

**Comment by FleyX** [comment]
自建坑很多，如果想要用自己域名的邮箱，可以使用腾讯企业邮或者阿里云企业邮，都能绑定自己的域名



fanxb.tl@gmail.com
 
发件人： Image
发送时间： 2020-09-11 15:07
收件人： FleyX/technology-note
抄送： FleyX; Author
主题： Re: [FleyX/technology-note] 最新ubuntu搭建公网个人邮件服务器(基于postfix，dovecot,mysql) | FleyX's space (#35)
按你的文档搭建的服务器收不到邮件，也没办法用Mac自带邮件客户端来连接？

**Comment by pz9042** [comment]
我也碰到了25端口的问题,阿里云禁止与其他服务器的25端口通信,说要用465,可不管我怎么配置,发送邮件还是连的25端口

**Comment by FleyX** [comment]
> 我也碰到了25端口的问题,阿里云禁止与其他服务器的25端口通信,说要用465,可不管我怎么配置,发送邮件还是连的25端口

哈哈，我也挣扎过，搞不定
