### ISSUE TITLE
springboot事务处理（自动/手动事务） | FleyX's space

### ISSUE THREAD

**Issue by FleyX** [FleyX/technology-note#51]
https://www.tapme.top/blog/detail/20190619/ 

 今天写代码的时候遇到了这样的一个问题：通过this.saveData()调用saveData方法，这个方法被@Transactional注解,期望在 saveData 抛出错误时能够回滚数据库,结果事务并没有生效。然后便对 spring boot 的事务进行了一次更深入的学习。 学习笔记如下： 要使用事务首先需要开启事务，在启动类中加入注解：@EnableTransactionManagemen

**Comment by lhz1165** [comment]
这应该是事务隔离级别的问题吧,给saveAll加一个事务注解应该也可以解决这个问题
