### ISSUE TITLE
springboot整合elasticsearch(基于es7.2和官方high level client) | 分享知识

### ISSUE THREAD

**Issue by FleyX** [FleyX/technology-note#55]
https://www.tapme.top/blog/detail/2019-07-29-14-59/ 

 前言最近写的一个个人项目(传送门：全终端云书签)中需要用到全文检索功能，目前 mysql，es 都可以做全文检索，mysql 胜在配置方便很快就能搞定上线(参考这里),不考虑上手难度，es 在全文检索方面是完胜 mysql 的。 最后决定使用 es。使用最新的 7.2 版本。java 客户端使用 es 官方的 high level client(官方文档),为什么用这个有以下几点原因：  jest

**Comment by albusxing** [comment]
es新人，有一个问题，不是已经有了  XXXRepository 了吗？为什么还要用RestHighLevelClient呢？

**Comment by FleyX** [comment]
XXXRepository 应该是jpa的方式，我个人不喜欢。high level client相当于数据库里的mybatis，比较喜欢这种写原生查询语句的。
